name: unvanquished-alpo
base: core24
version: 'v0.55.5'
summary: Real-time strategy game where aliens and humans fight for their survival
description: |
  Unvanquished is a free, open-source first-person strategy game shooter, pitting technologically advanced human soldiers against hordes of highly adaptable aliens. Players can choose from either team, providing for an entirely different experience on both sides, as humans focus on long-range firepower while aliens rely instead on quick movement and stealth. The goal of each match is to destroy the enemy base, preventing members of the opposing team from spawning. Upgrades for both teams are earned by a combination of individual performance and team map control, unlocking access to more powerful weapons and equipment for the humans, and larger, more ferocious forms for the aliens.

grade: stable
confinement: strict

apps:
  unvanquished:
    extensions: [gnome]
    command: unvanquished/daemon
    environment:
      SDL_AUDIODRIVER: pulse
    plugs:
      - network
      - network-bind
      - audio-playback
      - joystick
      - shmem
      
  daemonded:
    extensions: [gnome]
    command: unvanquished/daemonded
    plugs:
      - network
      - network-bind
      - shmem

plugs:
  shmem:
    interface: shared-memory
    private: true

parts:
  unvanquished:
    plugin: cmake
    source: https://github.com/Unvanquished/Unvanquished.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    source-type: git
    build-environment:
      - PYTHONPATH: $PYTHONPATH:/usr/lib/python3/dist-packages
    cmake-parameters:
      - -DPython3_EXECUTABLE=/usr/bin/python3
      - -DCMAKE_CXX_FLAGS="-Disfinite=std::isfinite"
    override-build: |
      
      cmake -S $CRAFT_PART_SRC -B . -DPython3_EXECUTABLE=/usr/bin/python3 -DCMAKE_CXX_FLAGS="-Disfinite=std::isfinite"
      cmake --build . -j$(nproc)

      $CRAFT_PART_SRC/download-paks pkg

      mkdir -p $CRAFT_PART_INSTALL/unvanquished
      mkdir -p $CRAFT_PART_INSTALL/unvanquished/pkg
      
      cp daemon $CRAFT_PART_INSTALL/unvanquished/
      cp daemonded $CRAFT_PART_INSTALL/unvanquished/
      cp nacl_* $CRAFT_PART_INSTALL/unvanquished/
      cp irt_core-*.nexe $CRAFT_PART_INSTALL/unvanquished/
      
      cp -rv pkg/* $CRAFT_PART_INSTALL/unvanquished/pkg/
      
    build-packages:
      - aria2
      - cmake
      - python3-yaml
      - python3-jinja2
      - build-essential
      - zlib1g-dev
      - libcurl4-gnutls-dev
      - libgmp-dev
      - libglew-dev
      - libopenal-dev
      - libopusfile-dev
      - liblua5.3-dev
      - libvorbis-dev
      - libjpeg-dev
      - libwebp-dev
      - libogg-dev
      - python-is-python3
    stage-packages:
      - zlib1g
      - liblua5.3-0
      - libopenal1
      - libopusfile0
      - libncurses6
      - libncursesw6
      - libasound2t64
      - libasound2-plugins
      - libpulse0
  
  gpu-2404:
    after: [unvanquished]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
      # Workaround for https://bugs.launchpad.net/snapd/+bug/2055273
      mkdir -p "${CRAFT_PRIME}/gpu-2404"
    prime:
    - bin/gpu-2404-wrapper
